import flags from 'country-flag-emoji-json';

// Map common nationality terms to country codes
const nationalityToCode: Record<string, string> = {
  // English nationality names
  'american': 'US',
  'british': 'GB',
  'english': 'GB',
  'french': 'FR',
  'german': 'DE',
  'italian': 'IT',
  'spanish': 'ES',
  'russian': 'RU',
  'chinese': 'CN',
  'japanese': 'JP',
  'korean': 'KR',
  'south korean': 'KR',
  'north korean': 'KP',
  'indian': 'IN',
  'brazilian': 'BR',
  'canadian': 'CA',
  'australian': 'AU',
  'mexican': 'MX',
  'dutch': 'NL',
  'polish': 'PL',
  'swedish': 'SE',
  'norwegian': 'NO',
  'danish': 'DK',
  'finnish': 'FI',
  'portuguese': 'PT',
  'greek': 'GR',
  'turkish': 'TR',
  'ukrainian': 'UA',
  'swiss': 'CH',
  'austrian': 'AT',
  'belgian': 'BE',
  'irish': 'IE',
  'scottish': 'GB',
  'welsh': 'GB',
  'czech': 'CZ',
  'hungarian': 'HU',
  'romanian': 'RO',
  'bulgarian': 'BG',
  'croatian': 'HR',
  'serbian': 'RS',
  'slovenian': 'SI',
  'slovak': 'SK',
  'estonian': 'EE',
  'latvian': 'LV',
  'lithuanian': 'LT',
  'thai': 'TH',
  'vietnamese': 'VN',
  'indonesian': 'ID',
  'malaysian': 'MY',
  'singaporean': 'SG',
  'filipino': 'PH',
  'egyptian': 'EG',
  'south african': 'ZA',
  'nigerian': 'NG',
  'kenyan': 'KE',
  'moroccan': 'MA',
  'algerian': 'DZ',
  'tunisian': 'TN',
  'libyan': 'LY',
  'ethiopian': 'ET',
  'ghanaian': 'GH',
  'tanzanian': 'TZ',
  'ugandan': 'UG',
  'rwandan': 'RW',
  'congolese': 'CD',
  'cameroonian': 'CM',
  'ivorian': 'CI',
  'senegalese': 'SN',
  'israeli': 'IL',
  'saudi': 'SA',
  'saudi arabian': 'SA',
  'emirati': 'AE',
  'qatari': 'QA',
  'kuwaiti': 'KW',
  'bahraini': 'BH',
  'omani': 'OM',
  'yemeni': 'YE',
  'jordanian': 'JO',
  'lebanese': 'LB',
  'syrian': 'SY',
  'iranian': 'IR',
  'iraqi': 'IQ',
  'afghan': 'AF',
  'pakistani': 'PK',
  'bangladeshi': 'BD',
  'sri lankan': 'LK',
  'nepalese': 'NP',
  'nepali': 'NP',
  'burmese': 'MM',
  'cambodian': 'KH',
  'laotian': 'LA',
  'mongolian': 'MN',
  'taiwanese': 'TW',
  'hong konger': 'HK',
  'macanese': 'MO',
  'argentinian': 'AR',
  'argentine': 'AR',
  'colombian': 'CO',
  'chilean': 'CL',
  'peruvian': 'PE',
  'venezuelan': 'VE',
  'ecuadorian': 'EC',
  'bolivian': 'BO',
  'paraguayan': 'PY',
  'uruguayan': 'UY',
  'cuban': 'CU',
  'dominican': 'DO',
  'puerto rican': 'PR',
  'jamaican': 'JM',
  'haitian': 'HT',
  'trinidadian': 'TT',
  'bahamian': 'BS',
  'barbadian': 'BB',
  'guatemalan': 'GT',
  'honduran': 'HN',
  'salvadoran': 'SV',
  'nicaraguan': 'NI',
  'costa rican': 'CR',
  'panamanian': 'PA',
  'new zealander': 'NZ',
  'kiwi': 'NZ',
  'fijian': 'FJ',
  'samoan': 'WS',
  'tongan': 'TO',
  'papuan': 'PG',
  'albanian': 'AL',
  'macedonian': 'MK',
  'montenegrin': 'ME',
  'bosnian': 'BA',
  'kosovar': 'XK',
  'moldovan': 'MD',
  'belarusian': 'BY',
  'georgian': 'GE',
  'armenian': 'AM',
  'azerbaijani': 'AZ',
  'kazakh': 'KZ',
  'uzbek': 'UZ',
  'turkmen': 'TM',
  'tajik': 'TJ',
  'kyrgyz': 'KG',
  'icelandic': 'IS',
  'luxembourgish': 'LU',
  'maltese': 'MT',
  'cypriot': 'CY',
  // Country names (for direct input)
  'usa': 'US',
  'uk': 'GB',
  'uae': 'AE',
  'united states': 'US',
  'united kingdom': 'GB',
  'great britain': 'GB',
  'france': 'FR',
  'germany': 'DE',
  'italy': 'IT',
  'spain': 'ES',
  'russia': 'RU',
  'china': 'CN',
  'japan': 'JP',
  'korea': 'KR',
  'south korea': 'KR',
  'north korea': 'KP',
  'india': 'IN',
  'brazil': 'BR',
  'canada': 'CA',
  'australia': 'AU',
  'mexico': 'MX',
  'netherlands': 'NL',
  'holland': 'NL',
  'poland': 'PL',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'finland': 'FI',
  'portugal': 'PT',
  'greece': 'GR',
  'turkey': 'TR',
  'ukraine': 'UA',
  'switzerland': 'CH',
  'austria': 'AT',
  'belgium': 'BE',
  'ireland': 'IE',
  'scotland': 'GB',
  'wales': 'GB',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'hungary': 'HU',
  'romania': 'RO',
  'bulgaria': 'BG',
  'croatia': 'HR',
  'serbia': 'RS',
  'slovenia': 'SI',
  'slovakia': 'SK',
  'estonia': 'EE',
  'latvia': 'LV',
  'lithuania': 'LT',
  'thailand': 'TH',
  'vietnam': 'VN',
  'indonesia': 'ID',
  'malaysia': 'MY',
  'singapore': 'SG',
  'philippines': 'PH',
  'egypt': 'EG',
  'south africa': 'ZA',
  'nigeria': 'NG',
  'kenya': 'KE',
  'morocco': 'MA',
  'algeria': 'DZ',
  'tunisia': 'TN',
  'libya': 'LY',
  'ethiopia': 'ET',
  'ghana': 'GH',
  'tanzania': 'TZ',
  'uganda': 'UG',
  'rwanda': 'RW',
  'congo': 'CD',
  'cameroon': 'CM',
  'ivory coast': 'CI',
  'senegal': 'SN',
  'israel': 'IL',
  'saudi arabia': 'SA',
  'united arab emirates': 'AE',
  'qatar': 'QA',
  'kuwait': 'KW',
  'bahrain': 'BH',
  'oman': 'OM',
  'yemen': 'YE',
  'jordan': 'JO',
  'lebanon': 'LB',
  'syria': 'SY',
  'iran': 'IR',
  'iraq': 'IQ',
  'afghanistan': 'AF',
  'pakistan': 'PK',
  'bangladesh': 'BD',
  'sri lanka': 'LK',
  'nepal': 'NP',
  'myanmar': 'MM',
  'burma': 'MM',
  'cambodia': 'KH',
  'laos': 'LA',
  'mongolia': 'MN',
  'taiwan': 'TW',
  'hong kong': 'HK',
  'macau': 'MO',
  'argentina': 'AR',
  'colombia': 'CO',
  'chile': 'CL',
  'peru': 'PE',
  'venezuela': 'VE',
  'ecuador': 'EC',
  'bolivia': 'BO',
  'paraguay': 'PY',
  'uruguay': 'UY',
  'cuba': 'CU',
  'dominican republic': 'DO',
  'puerto rico': 'PR',
  'jamaica': 'JM',
  'haiti': 'HT',
  'trinidad': 'TT',
  'bahamas': 'BS',
  'barbados': 'BB',
  'guatemala': 'GT',
  'honduras': 'HN',
  'el salvador': 'SV',
  'nicaragua': 'NI',
  'costa rica': 'CR',
  'panama': 'PA',
  'new zealand': 'NZ',
  'fiji': 'FJ',
  'samoa': 'WS',
  'tonga': 'TO',
  'papua new guinea': 'PG',
  'albania': 'AL',
  'north macedonia': 'MK',
  'macedonia': 'MK',
  'montenegro': 'ME',
  'bosnia': 'BA',
  'bosnia and herzegovina': 'BA',
  'kosovo': 'XK',
  'moldova': 'MD',
  'belarus': 'BY',
  'georgia': 'GE',
  'armenia': 'AM',
  'azerbaijan': 'AZ',
  'kazakhstan': 'KZ',
  'uzbekistan': 'UZ',
  'turkmenistan': 'TM',
  'tajikistan': 'TJ',
  'kyrgyzstan': 'KG',
  'iceland': 'IS',
  'luxembourg': 'LU',
  'malta': 'MT',
  'cyprus': 'CY',
  'monaco': 'MC',
  'liechtenstein': 'LI',
  'andorra': 'AD',
  'san marino': 'SM',
  'vatican': 'VA',
};

// Get all nationality options for autocomplete
export function getNationalitySuggestions(query: string): { name: string; emoji: string }[] {
  const normalized = query.toLowerCase().trim();
  if (!normalized) return [];
  
  const results: { name: string; emoji: string; priority: number }[] = [];
  const seen = new Set<string>();
  
  // Search through our mapping
  for (const [key, code] of Object.entries(nationalityToCode)) {
    if (key.includes(normalized)) {
      const country = flags.find(f => f.code === code);
      if (country && !seen.has(code)) {
        seen.add(code);
        // Capitalize first letter of each word
        const displayName = key.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
        results.push({
          name: displayName,
          emoji: country.emoji,
          priority: key.startsWith(normalized) ? 0 : 1
        });
      }
    }
  }
  
  // Also search in the flags library directly
  for (const flag of flags) {
    if (flag.name.toLowerCase().includes(normalized) && !seen.has(flag.code)) {
      seen.add(flag.code);
      results.push({
        name: flag.name,
        emoji: flag.emoji,
        priority: flag.name.toLowerCase().startsWith(normalized) ? 0 : 1
      });
    }
  }
  
  // Sort by priority then alphabetically, limit to 8
  return results
    .sort((a, b) => a.priority - b.priority || a.name.localeCompare(b.name))
    .slice(0, 8)
    .map(({ name, emoji }) => ({ name, emoji }));
}

export function getFlagEmoji(nationality: string): string | null {
  const normalized = nationality.toLowerCase().trim();
  const code = nationalityToCode[normalized];
  
  if (code) {
    const country = flags.find(f => f.code === code);
    return country?.emoji || null;
  }
  
  // Try to find by country name directly
  const directMatch = flags.find(f => 
    f.name.toLowerCase() === normalized || 
    f.code.toLowerCase() === normalized
  );
  
  return directMatch?.emoji || null;
}
